### ISSUE TITLE
Python bindings

### ISSUE THREAD

**Issue by CatarinaSilva** [marian-nmt/marian#118]
Hi, I have been using the python bindings and noticed the following behaviour. Although both the input and output are lists, when feeding several sentences:

`nmt.translate(['This is a text\n', 'This is another text\n', 'This is yet another text\n'])`

The output I get is all glued together:

`Out[7]: ['se trata de un textoeste es otro textoeste es todavía otro texto']`

My config is the following:

```
beam-size: 8
cpu-threads: 4
gpu-threads: 0
log-info: true
log-progress: true
max-length: 500
maxi-batch: 1
mini-batch: 1
n-best: false
no-debpe: false
normalize: yes
relative-paths: yes
return-alignment: False
return-soft-alignment: False
scorers:
  F0:
    path: model.npz
    type: Nematus
show-weights: false
softmax-filter:
  []
source-vocab: vocab.en
target-vocab: vocab.es
weights:
  F0: 1.0
wipo: True
```

Do you have any suggestions to make the bindings work for several sentences?

**Comment by beichao1314** [comment]
Maybe, you can try to change 'maxi-batch'  to 8, if you have 8 cores CPU when you use CPU to decoding.

**Comment by CatarinaSilva** [comment]
@beichao1314 thanks for your reply! 

I actually already tried playing around a bit with the maxi-batch and mini-batch parameters. It doesn't help. If I just set the maxi-batch to the number of CPU threads I am using, then I get the following configuration

```
beam-size: 8
cpu-threads: 4
gpu-threads: 0
log-info: true
log-progress: true
max-length: 500
maxi-batch: 4
mini-batch: 1
n-best: false
no-debpe: false
normalize: yes
relative-paths: yes
return-alignment: True
return-soft-alignment: True
scorers:
  F0:
    path: model.npz
    type: Nematus
show-weights: false
softmax-filter:
  []
source-vocab: vocab.en
target-vocab: vocab.pt
weights:
  F0: 1.0
wipo: True
```

and the result for 3 sentences (with alignment info in this case, but it is the same without it):

```
['esta é uma frase ||| 0-0 1-1 2-2 3-3 ||| 0.850212,0.129406,0.0183486,0.00147029,0.00056314 0.0296341,0.78709,0.0267329,0.13788,0.0186631 0.00449896,0.0251821,0.64578,0.302255,0.0222835 0.00323046,0.0249366,0.0442436,0.867071,0.0605185esta é mais outra frase ||| 0-0 1-1 2-2 3-2 4-3 ||| 0.764857,0.189181,0.0395252,0.00287525,0.00356141 0.0631526,0.7496,0.0728169,0.0853816,0.0290488 0.00548136,0.0250609,0.800307,0.115409,0.0537415 0.00161152,0.0131669,0.653158,0.123359,0.208704 5.13113e-05,0.000778234,0.00204129,0.944239,0.0528904e mais uma frase ||| 0-0 1-2 2-2 3-3 ||| 0.742159,0.164062,0.0392013,0.00480663,0.049771 0.176092,0.301363,0.323601,0.0916019,0.107342 0.0123835,0.0190836,0.704234,0.167051,0.0972481 0.0109834,0.00299264,0.0447919,0.791135,0.150097']
```

I also tried setting the mini-batch to the same number of the maxi-batch (in this case 4) but with that new configuration I can only translate lists with one sentence, more than that will give me a SEGFAULT:

```
nmt.translate(['This is one sentence', 'This is another sentence', 'And yet another sentence'])
Search took 0.354s
Segmentation fault: 11
```

There are two issues, I think:

* I would like to make use of the CPU threads so the decoding of a list is faster than just feeding one at a time

* Another thing is that it would be nice to be able to feed a list to translate and receive a list, even if you are not using threads. This is just a matter of usability I guess.
