### ISSUE TITLE
Get n-best list with soft alignment

### ISSUE THREAD

**Issue by CatarinaSilva** [marian-nmt/marian#159]
In Amun we can output the n-best list with size N (beam size) by using `--n-best`, but when combining this option with `--return-soft-alignments` the soft alignments are missing. Is there any way of still outputting them for each sentence in the n-best?

**Comment by hieuhoang** [comment]
can you tell me the exact command you've executed and a few lines of the output

**Comment by hieuhoang** [comment]
I erroneously confused n-best with alignment a while back and fixed it here https://github.com/marian-nmt/marian/commit/f072dca6a22946484e9f49daafb09e19bfa98143

If you haven't git pull since December 2017, you should do so and see if it works for you

**Comment by CatarinaSilva** [comment]
@hieuhoang  to make sure I wasn't using an outdated version I pulled and rebuild the binaries, and then I ran

Without n-best:
```
amun -c config.yml

[Mon Feb 19 19:49:33 2018] (I) Options: allow-unk: false
beam-size: 8
cpu-threads: 1
devices: [0]
gpu-threads: 0
log-info: info
log-progress: info
max-length: 500
maxi-batch: 8
mini-batch: 8
mini-batch-words: 0
n-best: false
no-debpe: false
normalize: yes
relative-paths: yes
return-alignment: True
return-nematus-alignment: false
return-soft-alignment: True
scorers:
  F0:
    path: /home/ubuntu/model.npz
    type: Nematus
show-weights: false
softmax-filter:
  []

max-length: 500
maxi-batch: 8
mini-batch: 8
mini-batch-words: 0
n-best: false
no-debpe: false
normalize: yes
relative-paths: yes
return-alignment: True
return-nematus-alignment: false
return-soft-alignment: True
scorers:
  F0:
    path: /home/ubuntu/model.npz
    type: Nematus
show-weights: false
softmax-filter:
  []
source-vocab:/home/ubuntu/vocab.en
target-vocab: /home/ubuntu/vocab.fr
tensor-cores: false
use-fused-softmax: true
weights:
  F0: 1.0
wipo: False

[Mon Feb 19 19:49:34 2018] (I) Loading scorers...
[Mon Feb 19 19:49:34 2018] (I) Loading model /home/ubuntu/model.npz
[Mon Feb 19 19:49:34 2018] (I) Model type: Nematus
useTensorCores_=0
[Mon Feb 19 19:49:34 2018] (I) Reading from stdin
[Mon Feb 19 19:49:34 2018] (I) Setting GPU thread count to 0
[Mon Feb 19 19:49:34 2018] (I) Total number of threads: 1
[Mon Feb 19 19:49:34 2018] (I) Reading input
This is an example sentence
Search took 0.603s
Best translation 0 : voici un exemple de phrase ||| 0-0 1-2 2-3 3-4 4-4 ||| 0.604638,0.0272236,0.0308805,0.0369153,0.0837833,0.216559 0.0390046,0.088417,0.677544,0.118775,0.0252787,0.0509802 0.00595125,0.0251566,0.0221004,0.389029,0.190247,0.367516 0.00415919,0.0086351,0.00843006,0.04782,0.601105,0.329851 0.00573996,0.000959744,0.00116261,0.00748611,0.688933,0.295718
voici un exemple de phrase ||| 0-0 1-2 2-3 3-4 4-4 ||| 0.604638,0.0272236,0.0308805,0.0369153,0.0837833,0.216559 0.0390046,0.088417,0.677544,0.118775,0.0252787,0.0509802 0.00595125,0.0251566,0.0221004,0.389029,0.190247,0.367516 0.00415919,0.0086351,0.00843006,0.04782,0.601105,0.329851 0.00573996,0.000959744,0.00116261,0.00748611,0.688933,0.295718
```

which as you can see generates the alignments, and then I ran with n-best:




```

[Mon Feb 19 19:52:06 2018] (I) Options: allow-unk: false
beam-size: 8
cpu-threads: 1
devices: [0]
gpu-threads: 0
log-info: info
log-progress: info
max-length: 500
maxi-batch: 8
mini-batch: 8
mini-batch-words: 0
n-best: True
no-debpe: false
normalize: yes
relative-paths: yes
return-alignment: True
return-nematus-alignment: false
return-soft-alignment: True
scorers:
  F0:
    path: /home/ubuntu/model.npz
    type: Nematus
show-weights: false
softmax-filter:
  []
source-vocab:/home/ubuntu/vocab.en
target-vocab: /home/ubuntu/vocab.fr
tensor-cores: false
use-fused-softmax: true
weights:
  F0: 1.0
wipo: False

[Mon Feb 19 19:52:07 2018] (I) Loading scorers...
[Mon Feb 19 19:52:07 2018] (I) Loading model /home/ubuntu/model.npz
[Mon Feb 19 19:52:07 2018] (I) Model type: Nematus
useTensorCores_=0
[Mon Feb 19 19:52:07 2018] (I) Reading from stdin
[Mon Feb 19 19:52:07 2018] (I) Setting GPU thread count to 0
[Mon Feb 19 19:52:07 2018] (I) Total number of threads: 1
[Mon Feb 19 19:52:07 2018] (I) Reading input
This is an example sentence
Search took 0.592s
Best translation 0 : 0 ||| voici un exemple de phrase ||| 0-0 1-2 2-3 3-4 4-4 ||| F0= -1.289 ||| -0.215
0 ||| voici une phrase d&apos; exemple ||| 0-0 1-2 2-3 3-4 4-4 ||| F0= -2.620 ||| -0.437
0 ||| voici une phrase d&apos; exemple . ||| 0-0 1-2 2-3 3-4 4-4 ||| F0= -3.155 ||| -0.451
0 ||| ceci est une phrase d&apos; exemple . ||| 0-0 1-2 2-3 3-4 4-4 ||| F0= -3.940 ||| -0.492
0 ||| ceci est une phrase d&apos; exemple ||| 0-0 1-2 2-3 3-4 4-4 ||| F0= -3.676 ||| -0.525
0 ||| ceci est un exemple de phrase ||| 0-0 1-2 2-3 3-4 4-4 ||| F0= -3.687 ||| -0.527
0 ||| il s&apos; agit d&apos; une phrase d&apos; exemple ||| 0-0 1-2 2-3 3-4 4-4 ||| F0= -4.752 ||| -0.528
0 ||| c&apos; est un exemple de phrase ||| 0-0 1-2 2-3 3-4 4-4 ||| F0= -3.711 ||| -0.530
0 ||| voici un exemple de phrase ||| 0-0 1-2 2-3 3-4 4-4 ||| F0= -1.289 ||| -0.215
0 ||| voici une phrase d&apos; exemple ||| 0-0 1-2 2-3 3-4 4-4 ||| F0= -2.620 ||| -0.437
0 ||| voici une phrase d&apos; exemple . ||| 0-0 1-2 2-3 3-4 4-4 ||| F0= -3.155 ||| -0.451
0 ||| ceci est une phrase d&apos; exemple . ||| 0-0 1-2 2-3 3-4 4-4 ||| F0= -3.940 ||| -0.492
0 ||| ceci est une phrase d&apos; exemple ||| 0-0 1-2 2-3 3-4 4-4 ||| F0= -3.676 ||| -0.525
0 ||| ceci est un exemple de phrase ||| 0-0 1-2 2-3 3-4 4-4 ||| F0= -3.687 ||| -0.527
0 ||| il s&apos; agit d&apos; une phrase d&apos; exemple ||| 0-0 1-2 2-3 3-4 4-4 ||| F0= -4.752 ||| -0.528
0 ||| c&apos; est un exemple de phrase ||| 0-0 1-2 2-3 3-4 4-4 ||| F0= -3.711 ||| -0.530

```

Which generates only the alignments, although the `return-soft-alignments` is set to` True`
