### ISSUE TITLE
Error while translating with CPU version of Amun

### ISSUE THREAD

**Issue by Proyag** [marian-nmt/marian#165]
Hi,

The CPU version of Amun (compiled with the `-DCUDA=off` cmake flag) fails with the following error:
```
terminate called after throwing an instance of 'YAML::InvalidNode'
  what():  invalid node; this may result from using a map iterator as a sequence iterator, or vice-versa
Aborted (core dumped)
```

With the same config file, Amun compiled with GPU support works as expected.
I'm using the same version of the Marian repo (fe55ddc) and the same model and config; the only difference is in compilation with or without GPU support.

Here's the Amun config (model.npz.amun.yml):
```
source-vocab: baseline.en-pt/trainset.proc.bpe.en.yml
target-vocab: baseline.en-pt/trainset.proc.bpe.pt.yml
devices:
  - 0
normalize: true
beam-size: 12
relative-paths: false
scorers:
  F0:
    path: baseline.en-pt/model.npz
    type: Nematus
weights:
  F0: 1
```

And I've attached the model config: [model.npz.yml](https://github.com/marian-nmt/marian/files/1811326/model.npz.yml.txt)
