### ISSUE TITLE
segmentation fault at empty input to amun decoder

### ISSUE THREAD

**Issue by domjehle** [marian-nmt/marian#187]
Hi,

I have recently found out that in certain cases our preprocessing sends an empty segment to amun and then it crashes. I reproduced it on the tagged version 1.4.0., with CPU decoding, and used a model from http://data.statmt.org/wmt17_systems/en-de/ for reproduction (see below). I can't currently test on GPU.

````
amun -m model.l2r.ens1.npz -s vocab.en.json -t vocab.de.json --cpu-threads 8 --gpu-threads 0 <<< ""
[Wed June 6 09:34:56 2018] (I) Options: allow-unk: false
beam-size: 12
cpu-threads: 8
devices: [0]
gpu-threads: 0
log-info: info
log-progress: info
max-length: 500
max-length-multiple: 3
maxi-batch: 1
mini-batch: 1
mini-batch-words: 0
n-best: false
no-debpe: false
normalize: false
relative-paths: false
return-alignment: false
return-nematus-alignment: false
return-soft-alignment: false
scorers:
  F0:
    path: model.l2r.ens1.npz
    type: Nematus
show-weights: false
softmax-filter:
  []
source-vocab:
  - vocab.en.json
target-vocab: vocab.de.json
tensor-cores: false
use-fused-softmax: true
weights:
  F0: 1
wipo: false

[Wed June 6 09:34:57 2018] (I) Loading scorers...
[Wed June 6 09:34:57 2018] (I) Loading model model.l2r.ens1.npz
[Wed June 6 09:34:57 2018] (I) Model type: Nematus
[Wed June 6 09:35:00 2018] (I) Reading from stdin
[Wed June 6 09:35:00 2018] (I) Setting GPU thread count to 0
[Wed June 6 09:35:00 2018] (I) Total number of threads: 8
[Wed June 6 09:35:00 2018] (I) Reading input
Segmentation fault (core dumped)
````

Sure, it may not be standard behavior to send empty sources, but it was not expected either that amun would die... We are trying out best to work around this.

Best regards,
Dominic
