### ISSUE TITLE
YAML::ParserException when decoding with amun on CPU

### ISSUE THREAD

**Issue by vikrantsharma7** [marian-nmt/marian#210]
OS: Ubuntu 16.04.4
CMake: 3.5.1
GCC: 5.4.0
Boost: 1.58
Marian: bda9b18

Trained a model with the following command on a GPU machine with similar configuration as above.
```
./marian/build/marian \
  --train-sets train_src train_tgt \
  --vocabs vocab.en vocab.or \
  --model model.npz \
  --max-length 250 -w 5120
```
Copied the `model.npz` file created after 10000 updates to the CPU machine.
Tried translating with the following command (Assuming pwd to be the `build` directory):
```
./amun -m model.npz -s vocab.en -t vocab.or <<< "Hello"
```
which results in the following:
```
[Tue Sept 11 17:26:46 2018] (I) Options: allow-unk: false
beam-size: 12
cpu-threads: 1
log-info: info
log-progress: info
max-length: 500
max-length-multiple: 3
maxi-batch: 1
mini-batch: 1
mini-batch-words: 0
n-best: false
no-debpe: false
normalize: false
relative-paths: false
return-alignment: false
return-nematus-alignment: false
return-soft-alignment: false
scorers:
  F0:
    path: model.npz
    type: Nematus
show-weights: false
softmax-filter:
  []
source-vocab:
  - vocab.en
target-vocab: vocab.or
use-fused-softmax: true
weights:
  F0: 1
wipo: false

terminate called after throwing an instance of 'YAML::ParserException'
  what():  yaml-cpp: error at line 35, column 1: illegal map value
Aborted (core dumped)
```
Help please?
